version: '3.7'
services:
    db:
      container_name: mariadb
      image: mariadb:latest
      restart: always
      ports:
        - 3306:3306
      volumes:
        - /d/5.Workspace/3.Docker/99.Volume/1.MariaDB/data:/var/lib/mysql
        - /d/5.Workspace/3.Docker/99.Volume/1.MariaDB/config:/etc/mysql/conf.d
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        TZ: Asia/Seoul